#pragma once

#define PET_RELAY_WPM 0
#define PET_RELAY_KEY_PRESS 1
#define PET_RELAY_KEY_RELEASE 2

#define PET_RELAY_HID_USAGE_PAGE_KEY 0x07
#define PET_RELAY_HID_KEY_SPACE 0x2C
#define PET_RELAY_HID_KEY_LCTRL 0xE0
#define PET_RELAY_HID_KEY_RCTRL 0xE4
