/*
 * Neko pet frames, generated by tools/convert_qmk_pet.py.
 */

#pragma once

#include <lvgl.h>

#define NEKO_FRAME_W 51
#define NEKO_FRAME_H 51
#define NEKO_FRAMES_PER_STATE 2

extern const lv_img_dsc_t *const neko_idle[2];
extern const lv_img_dsc_t *const neko_walk[2];
extern const lv_img_dsc_t *const neko_run[2];
extern const lv_img_dsc_t *const neko_caps[2];
extern const lv_img_dsc_t *const neko_ctrl[8];
extern const lv_img_dsc_t *const neko_scroll[16];
